#7-1 PROGRAMMING EXERCISE
#DESIGN A PROGRAM THAT ASKS THE USER TO ENTER
#A STORE'S SALES FOR EACH DAY OF THE WEEK.
#THE AMOUNTS SHOULD BE STORED IN A LIST. USE
#A LOOP TO CALCULATE THE TOTAL SALES FOR THE WEEK
#AND DISPLAY THE RESULT.


# CREATE LIST FOR DAYS OF THE WEEK
days_of_week = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']

# CREATE EMPTY SALES LIST TO STORE USER INPUT
sales = []

# RECEIVE USER INPUT FOR EACH DAY OF THE WEEK USING FOR LOOP
for day in days_of_week:
    daily_sales = float(input(f"ENTER STORE'S SALE FOR {day}:$ ")) #GET USER INPUT FOR SALES AMOUNT
    sales.append(daily_sales) #APPEND USER INPUT TO THE SALES LIST

# CALC TOTAL SALES USING FOR LOOP
total_sales = 0 #INTIALIZE TOTAL SALES
for daily_sales in sales:
    total_sales += daily_sales #ADD TOTAL DAILY SALES

# DISPLAY TOTAL SALES
print(f"TOTAL SALES OF THE WEEK: ${total_sales:.2f}")

